### PR TITLE
Fix parsing error caused by HN markup changes

### PR DESCRIPTION
**Pull request by marcboquet**
Source site now is in its own `span` tag

### CODE REVIEW

**Comment by marcboquet** [comment]
I have no idea how xpath works, so it's possible that it's an awful way to fix it...

**Comment by MarcoSero** [comment]
apple-keynote-2015-clapping

**Comment by MarcoSero** [comment]
Just had a quick look.. I don't think this is going to work unfortunately.

``` swift
.map { $0.xpath("//span[@class='sitestr']")?.first?.contents
```

is querying the _whole_ document for `span` components of class `sitestr`and always taking the first, so this will always result in the same URL displayed for every different story.

**Comment by marcboquet** [comment]
Ugh, something like this is what I feared xpath would be doing. It should be better now

**Comment by MarcoSero** [comment]
:100: Thank you for doing this!

**Pull request merged**
