### PR TITLE
Update for Xcode 7

### PR DESCRIPTION
**Pull request by jlampa**
Fixes issue #21

### CODE REVIEW

**Comment by jlampa** [comment]
This PR makes the project compile in Xcode 7 (Swift 2 syntax + updated pods) and fixes some problems caused by markup changes.

**Comment by MarcoSero** [comment]
Thank you _so much_ for doing it :heart:. Everything seems perfect :sparkles: 

Could you please just double check if favicon still work? We might need to set `NSAllowsArbitraryLoads` in the `Info.plist`.

**Comment by jlampa** [comment]
Good catch! Fixed.

**Comment by MarcoSero** [comment]
:sparkling_heart:

**Pull request merged**
